_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    # RES2_OUT_CHANNELS: 64
  DiffusionDet:
    NUM_PROPOSALS: 300  # Reduced from 500 for lower memory usage
    NUM_CLASSES: 6  # 6 wildlife species
DATASETS:
  TRAIN: ("wildlifemapper_train",)
  TEST:  ("wildlifemapper_val",)
SOLVER:
  IMS_PER_BATCH: 6  # Reduced from 16 for lower memory usage
  BASE_LR: 0.0000125  # Scaled down from 0.000025 (half batch size = half LR)
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  AMP:
    ENABLED: True  # Enable mixed precision training for memory savings
INPUT:
  MIN_SIZE_TRAIN: (640,)  # Fixed 640x640
  MAX_SIZE_TRAIN: 640     # Fixed 640x640
  MIN_SIZE_TEST: 640      # Fixed 640x640
  MAX_SIZE_TEST: 640      # Fixed 640x640
  CROP:
    ENABLED: False        # Disable crop for fixed size
  FORMAT: "RGB"
DATALOADER:
  NUM_WORKERS: 12  # Reduced from 4 for lower memory usage
